# Generated by Django 4.2.26 on 2026-06-12 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('target_region', models.CharField(blank=True, max_length=120)),
                ('target_population', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_type', models.CharField(choices=[('cluster', 'Cluster'), ('persona', 'Persona'), ('system', 'System'), ('aggregator', 'Aggregator')], max_length=24)),
                ('text', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryTopic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('freshness_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('importance_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_topics', to='simulator.agenda')),
            ],
            options={
                'ordering': ['-importance_score', '-freshness_score', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PredictionRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.TextField(blank=True)),
                ('opinion_distribution', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_runs', to='simulator.agenda')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShockEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prediction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shock_events', to='simulator.predictionrun')),
            ],
            options={
                'ordering': ['prediction_run', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PopulationCluster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('demographics', models.JSONField(blank=True, default=dict)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('traits', models.JSONField(blank=True, default=dict)),
                ('media_diet', models.JSONField(blank=True, default=list)),
                ('pain_points', models.JSONField(blank=True, default=list)),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight_source', models.CharField(choices=[('explicit', 'Explicit'), ('llm_estimated', 'LLM estimated'), ('equal_default', 'Equal default')], default='equal_default', max_length=24)),
                ('confidence', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='simulator.agenda')),
            ],
            options={
                'ordering': ['agenda', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonaInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('current_memory_summary', models.TextField(blank=True)),
                ('recent_memory_summary', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='simulator.populationcluster')),
            ],
            options={
                'ordering': ['cluster', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemoryTopicLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_reason', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='simulator.memorytopic')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to='simulator.conversationturn')),
            ],
        ),
        migrations.AddField(
            model_name='memorytopic',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_topics', to='simulator.populationcluster'),
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI')], max_length=24)),
                ('model', models.CharField(max_length=120)),
                ('purpose', models.CharField(max_length=120)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'purpose', 'status'], name='simulator_l_provide_5f8683_idx'), models.Index(fields=['created_at'], name='simulator_l_created_54b337_idx')],
            },
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='simulator.populationcluster'),
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='persona_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='simulator.personainstance'),
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='prediction_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='simulator.predictionrun'),
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='shock_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='simulator.shockevent'),
        ),
        migrations.CreateModel(
            name='ClusterState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stance', models.CharField(max_length=120)),
                ('sentiment', models.CharField(blank=True, max_length=120)),
                ('acceptance_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('behavior_intent', models.JSONField(blank=True, default=dict)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('reasoning', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='simulator.populationcluster')),
                ('prediction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_states', to='simulator.predictionrun')),
                ('shock_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_states', to='simulator.shockevent')),
            ],
            options={
                'ordering': ['shock_event__order', 'cluster__name'],
            },
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['created_at'], name='simulator_a_created_19b8ce_idx'),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['title'], name='simulator_a_title_3bc1b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='shockevent',
            constraint=models.UniqueConstraint(fields=('prediction_run', 'order'), name='unique_shock_order_per_run'),
        ),
        migrations.AddIndex(
            model_name='predictionrun',
            index=models.Index(fields=['agenda', 'status'], name='simulator_p_agenda__d38471_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionrun',
            index=models.Index(fields=['created_at'], name='simulator_p_created_36e688_idx'),
        ),
        migrations.AddIndex(
            model_name='populationcluster',
            index=models.Index(fields=['agenda', 'name'], name='simulator_p_agenda__399c42_idx'),
        ),
        migrations.AddIndex(
            model_name='populationcluster',
            index=models.Index(fields=['agenda', 'weight'], name='simulator_p_agenda__498e93_idx'),
        ),
        migrations.AddConstraint(
            model_name='populationcluster',
            constraint=models.UniqueConstraint(fields=('agenda', 'name'), name='unique_cluster_name_per_agenda'),
        ),
        migrations.AddIndex(
            model_name='memorytopiclink',
            index=models.Index(fields=['topic', 'confidence'], name='simulator_m_topic_i_80241a_idx'),
        ),
        migrations.AddIndex(
            model_name='memorytopiclink',
            index=models.Index(fields=['turn'], name='simulator_m_turn_id_0b9691_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorytopiclink',
            constraint=models.UniqueConstraint(fields=('topic', 'turn'), name='unique_topic_turn_link'),
        ),
        migrations.AddIndex(
            model_name='memorytopic',
            index=models.Index(fields=['agenda', 'cluster'], name='simulator_m_agenda__891144_idx'),
        ),
        migrations.AddIndex(
            model_name='memorytopic',
            index=models.Index(fields=['importance_score', 'freshness_score'], name='simulator_m_importa_335b72_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorytopic',
            constraint=models.UniqueConstraint(fields=('agenda', 'cluster', 'title'), name='unique_topic_per_cluster'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['prediction_run', 'created_at'], name='simulator_c_predict_1eb597_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['shock_event', 'created_at'], name='simulator_c_shock_e_279a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['cluster', 'created_at'], name='simulator_c_cluster_55eb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterstate',
            index=models.Index(fields=['prediction_run', 'shock_event'], name='simulator_c_predict_6215f5_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterstate',
            index=models.Index(fields=['cluster', 'created_at'], name='simulator_c_cluster_89281b_idx'),
        ),
        migrations.AddConstraint(
            model_name='clusterstate',
            constraint=models.UniqueConstraint(fields=('prediction_run', 'shock_event', 'cluster'), name='unique_cluster_state_per_shock'),
        ),
    ]
